CREATE TABLE [dbo].[prdlin_unavail_sch] (
    [unavail_id]       NVARCHAR (30) NOT NULL,
    [prdlin]           NVARCHAR (20) NOT NULL,
    [wh_id]            NVARCHAR (32) NOT NULL,
    [begdte]           DATETIME      NOT NULL,
    [enddte]           DATETIME      NOT NULL,
    [unavail_reacod]   NVARCHAR (40) NULL,
    [ins_dt]           DATETIME      NULL,
    [last_upd_dt]      DATETIME      NULL,
    [ins_user_id]      NVARCHAR (40) NULL,
    [last_upd_user_id] NVARCHAR (40) NULL,
    CONSTRAINT [prdlin_unavsch_pk] PRIMARY KEY CLUSTERED ([unavail_id] ASC) WITH (FILLFACTOR = 90)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Production Line Unavailable Schedules', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the unavailable schedule in system. This value is generated by the system when the unavailable schedule is created. ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'unavail_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Warehouse ID.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'wh_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Begin date of unavailable periord.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'begdte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'End date of unavailable periord.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'enddte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The reason code that why the prudction is unavailable. User can define their own reason code. ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'unavail_reacod';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The date the row was inserted', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'ins_dt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The date the row was last updated', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'last_upd_dt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The user id of the person who created the row', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'ins_user_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The user id of the person who updated the row most recently', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'prdlin_unavail_sch', @level2type = N'COLUMN', @level2name = N'last_upd_user_id';

