CREATE TABLE [dbo].[rfidact] (
    [rfidact_id]       NVARCHAR (10) NOT NULL,
    [trndte]           DATETIME      NULL,
    [dlytrn_id]        NVARCHAR (10) NOT NULL,
    [actcod]           NVARCHAR (40) NOT NULL,
    [lodnum]           NVARCHAR (30) NULL,
    [subnum]           NVARCHAR (30) NULL,
    [read_flg]         INT           DEFAULT ((0)) NULL,
    [lodtag]           NVARCHAR (40) NULL,
    [subtag]           NVARCHAR (40) NULL,
    [prtnum]           NVARCHAR (50) NULL,
    [prt_client_id]    NVARCHAR (32) NULL,
    [lodurn]           NVARCHAR (60) NULL,
    [suburn]           NVARCHAR (60) NULL,
    [arcdte]           DATETIME      NULL,
    [u_version]        INT           NULL,
    [ins_dt]           DATETIME      NULL,
    [last_upd_dt]      DATETIME      NULL,
    [ins_user_id]      NVARCHAR (40) NULL,
    [last_upd_user_id] NVARCHAR (40) NULL,
    [rowid]            INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [rfidact_pk] PRIMARY KEY CLUSTERED ([rfidact_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [rfidact_readflg_ck] CHECK ([read_flg]=(0) OR [read_flg]=(1))
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [rfidact_rowid]
    ON [dbo].[rfidact]([rowid] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [rfidact_dlytrn_id]
    ON [dbo].[rfidact]([dlytrn_id] ASC) WITH (FILLFACTOR = 90);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The RFID Activity table is used to log RFID activity within the system.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the RFID activity in the system. This value is generated by the system when a new RFID activity is logged.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'rfidact_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date and time the RFID activity occurred.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'trndte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Daily Transaction id from the related Daily Transaction table', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'dlytrn_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Activity code representing the type of RFID activity.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'actcod';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Load Number contain the RFID tag.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'lodnum';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'ub-Load Number containing the RFID tag.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'subnum';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Indicator whether the RFID tag was read or assumed to be part of activity.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'read_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The load level tag for the activity.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'lodtag';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The sub-load level tag for the activity.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'subtag';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The item number represented by the tag, could be MIXED.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'prtnum';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The item client id represented by the tag.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'prt_client_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The Uniform Resource Name representing the pallet tag.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'lodurn';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The Uniform Resource Name representing the carton tag.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'suburn';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date and time the RFID activity was archived.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'arcdte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The version number', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'u_version';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The date the row was inserted', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'ins_dt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The date the row was last updated', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'last_upd_dt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The user id of the person who created the row', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'ins_user_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The user id of the person who updated the row most recently', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rfidact', @level2type = N'COLUMN', @level2name = N'last_upd_user_id';

