CREATE TABLE [dbo].[rpt_archive] (
    [filename]     NVARCHAR (512)  NOT NULL,
    [rpt_id]       NVARCHAR (30)   NOT NULL,
    [descr]        NVARCHAR (250)  NULL,
    [app_srv_host] NVARCHAR (256)  NULL,
    [gen_dt]       DATETIME        NULL,
    [expire_dt]    DATETIME        NULL,
    [file_size]    INT             NULL,
    [usr_id]       NVARCHAR (40)   NULL,
    [prod_id]      NVARCHAR (10)   NULL,
    [parm_val]     NVARCHAR (2000) NULL,
    [dsp_rpt_id]   NVARCHAR (250)  NULL,
    [status]       NVARCHAR (1)    NULL,
    [purge_uuid]   NVARCHAR (36)   NULL,
    CONSTRAINT [rpt_archive_pk] PRIMARY KEY CLUSTERED ([filename] ASC) WITH (FILLFACTOR = 90)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This table is used to store archive information for reports generated by the reporter system.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The name of the archive report file.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'filename';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Report ID - The report identifier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'rpt_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The description of the report as entered by the person or process executing the report', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'descr';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The application service url for the application server on which this report was run.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'app_srv_host';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date and time the report was executed. ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'gen_dt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date and time the report archive will expire and be available for purging.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'expire_dt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Size of the archived file.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'file_size';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The user who executed the report', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'usr_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Product ID -  The product identifier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'prod_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The parameters passed to the report', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'rpt_archive', @level2type = N'COLUMN', @level2name = N'parm_val';

