CREATE TABLE [dbo].[slot_attribute] (
    [attr_name]          NVARCHAR (30)   NOT NULL,
    [il_typ]             NVARCHAR (10)   NOT NULL,
    [set_def_flg]        INT             NULL,
    [sort_def_flg]       INT             NULL,
    [attr_typ]           NVARCHAR (20)   NOT NULL,
    [attr_user_txt]      NVARCHAR (30)   NOT NULL,
    [var_nam]            NVARCHAR (40)   NULL,
    [wh_req_flg]         INT             NULL,
    [attr_req_str]       NVARCHAR (40)   NULL,
    [table_name]         NVARCHAR (30)   NOT NULL,
    [attr_sel_cl]        NVARCHAR (2000) NOT NULL,
    [attr_alias]         NVARCHAR (50)   NULL,
    [rounding_factor]    INT             NULL,
    [group_sel_flg]      INT             NULL,
    [tlvl_column_sel]    NVARCHAR (60)   NULL,
    [vel_dt_str_1]       NVARCHAR (2000) NULL,
    [vel_dt_str_2]       NVARCHAR (2000) NULL,
    [union_cd]           NUMERIC (1)     NOT NULL,
    [union_sel_cl]       NVARCHAR (2000) NULL,
    [union_exst_cl]      NVARCHAR (2000) NULL,
    [match_rule_var_nam] NVARCHAR (50)   NULL,
    [ctrl_user_id]       NVARCHAR (40)   NULL,
    [ctrl_dt]            DATETIME        NULL,
    CONSTRAINT [slot_attribute_pk] PRIMARY KEY CLUSTERED ([attr_name] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [slot_attr_grpseflg] CHECK ([group_sel_flg]=(0) OR [group_sel_flg]=(1)),
    CONSTRAINT [slot_attr_set_dflg] CHECK ([set_def_flg]=(0) OR [set_def_flg]=(1)),
    CONSTRAINT [slot_attr_srt_dflg] CHECK ([sort_def_flg]=(0) OR [sort_def_flg]=(1)),
    CONSTRAINT [slot_attr_wh_rqflg] CHECK ([wh_req_flg]=(0) OR [wh_req_flg]=(1))
);

