CREATE TABLE [dbo].[trlract] (
    [trlract_id]     NVARCHAR (10)   NOT NULL,
    [trndte]         DATETIME        NULL,
    [actcod]         NVARCHAR (40)   NOT NULL,
    [trlr_id]        NVARCHAR (20)   NOT NULL,
    [wh_id]          NVARCHAR (32)   NOT NULL,
    [carcod]         NVARCHAR (10)   NULL,
    [trlr_num]       NVARCHAR (20)   NULL,
    [trlr_stat]      NVARCHAR (8)    NULL,
    [yard_loc]       NVARCHAR (20)   NULL,
    [yard_loc_wh_id] NVARCHAR (32)   NULL,
    [trlr_cod]       NVARCHAR (4)    NULL,
    [car_move_id]    NVARCHAR (10)   NULL,
    [trknum]         NVARCHAR (20)   NULL,
    [autogen_flg]    INT             NULL,
    [client_id]      NVARCHAR (32)   NULL,
    [tractor_num]    NVARCHAR (10)   NULL,
    [trlr_cond]      NVARCHAR (10)   NULL,
    [appt_id]        NVARCHAR (10)   NULL,
    [asset_tag]      NVARCHAR (40)   NULL,
    [mod_collst]     NVARCHAR (2000) NULL,
    [mod_vallst]     NVARCHAR (2000) NULL,
    [moddte]         DATETIME        NULL,
    [mod_usr_id]     NVARCHAR (40)   NULL,
    [rowid]          INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [trlract_pk] PRIMARY KEY CLUSTERED ([trlract_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [trlract_autgnflgck] CHECK ([autogen_flg]=(0) OR [autogen_flg]=(1))
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [trlract_rowid]
    ON [dbo].[trlract]([rowid] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [trlract_idx1]
    ON [dbo].[trlract]([carcod] ASC, [trlr_num] ASC) WITH (FILLFACTOR = 90);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The Trailer Activity table is used to log movement and modifications to receiving and shipping trailers in the system.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the trailer activity in the system. This value is generated by the system when a new trailer activity is logged.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trlract_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date and time the trailer activity occurred.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trndte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Activity code representing the type of trailer activity.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'actcod';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the trailer in the system.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trlr_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The ID of the warehouse.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'wh_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Carrier for which this trailer transports inventory. A carrier code is only required for Shipping trailers, but may be applied to Receiving trailers.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'carcod';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'User identification for the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trlr_num';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Trailer status of the trailer. The trailer status is updated by the system to indicate the current condition and location of the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trlr_stat';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Dock or yard location where the trailer is physically located.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'yard_loc';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The ID of the warehouse where the yard location of the trailer is.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'yard_loc_wh_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Defines the trailer as either a Shipping or Receiving trailer. Trailer Code options are RCV or SHIP.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trlr_cod';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The Carrier Move ID assigned to the trailer. This only applies to Shipping trailers.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'car_move_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Receiving Truck number assigned to the trailer. This only applies to receiving trailers, or receiving trailers that have been turned around for shipping.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trknum';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Flags the trailer as having been automatically generated when the user chose to automatically generate the carrier move and stops.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'autogen_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Client ID (owner) of the trailer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'client_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The tractor or cab number of the trailer, different than the customer known trailer number', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'tractor_num';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The condition of the trailer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'trlr_cond';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The appointment number assigned to the trailer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'appt_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Asset tag identifier for the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'asset_tag';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The list of columns that changed when a change was logged for a trailer. ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'mod_collst';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The list of values that were changed when a change was logged for either a trailer. ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'mod_vallst';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Last date this trailer activity was modified.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'moddte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Last user to modify this trailer activity.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlract', @level2type = N'COLUMN', @level2name = N'mod_usr_id';

