CREATE TABLE [dbo].[trlr] (
    [trlr_id]           NVARCHAR (20)   NOT NULL,
    [carcod]            NVARCHAR (10)   NULL,
    [trlr_num]          NVARCHAR (20)   NOT NULL,
    [trlr_stat]         NVARCHAR (8)    NULL,
    [trlr_typ]          NVARCHAR (4)    NULL,
    [trlr_size]         INT             NULL,
    [refrig_flg]        INT             NULL,
    [trlr_broker]       NVARCHAR (20)   NULL,
    [trlr_seal1]        NVARCHAR (30)   NULL,
    [trlr_seal2]        NVARCHAR (30)   NULL,
    [trlr_seal3]        NVARCHAR (30)   NULL,
    [trlr_seal4]        NVARCHAR (30)   NULL,
    [stoloc]            NVARCHAR (20)   NULL,
    [yard_loc]          NVARCHAR (20)   NULL,
    [yard_stat]         NVARCHAR (8)    NULL,
    [trlr_wgt]          NUMERIC (19, 4) NULL,
    [driver_nam]        NVARCHAR (40)   NULL,
    [driver_lic_num]    NVARCHAR (40)   NULL,
    [close_dte]         DATETIME        NULL,
    [pend_dte]          DATETIME        NULL,
    [dispatch_dte]      DATETIME        NULL,
    [autogen_flg]       INT             NULL,
    [hot_flg]           INT             DEFAULT ((0)) NULL,
    [trlr_cod]          NVARCHAR (4)    NOT NULL,
    [turn_flg]          INT             DEFAULT ((0)) NULL,
    [delv_flg]          INT             DEFAULT ((0)) NULL,
    [appt_id]           NVARCHAR (10)   NULL,
    [arrdte]            DATETIME        NULL,
    [client_id]         NVARCHAR (32)   NULL,
    [sec_trlr_num]      NVARCHAR (20)   NULL,
    [tractor_num]       NVARCHAR (10)   NULL,
    [trlr_cond]         NVARCHAR (10)   NULL,
    [pal_slot_flg]      INT             NULL,
    [stoloc_wh_id]      NVARCHAR (32)   NULL,
    [yard_loc_wh_id]    NVARCHAR (32)   NULL,
    [orig_trlr_num]     NVARCHAR (20)   NULL,
    [trlr_ref]          NVARCHAR (20)   NULL,
    [min_trlr_axle_pos] NUMERIC (19, 4) NULL,
    [max_trlr_axle_pos] NUMERIC (19, 4) NULL,
    [front_axle_pos]    NUMERIC (19, 4) NULL,
    [moddte]            DATETIME        NULL,
    [mod_usr_id]        NVARCHAR (40)   NULL,
    [live_load_flg]     INT             DEFAULT ((0)) NULL,
    [safe_sts]          NVARCHAR (1)    DEFAULT (N'U') NOT NULL,
    CONSTRAINT [trlr_pk] PRIMARY KEY CLUSTERED ([trlr_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [autogen_flg_ck] CHECK ([autogen_flg]=(0) OR [autogen_flg]=(1)),
    CONSTRAINT [delv_flg_ck] CHECK ([delv_flg]=(0) OR [delv_flg]=(1)),
    CONSTRAINT [hot_flg_ck] CHECK ([hot_flg]=(0) OR [hot_flg]=(1)),
    CONSTRAINT [live_load_flg_ck] CHECK ([live_load_flg]=(0) OR [live_load_flg]=(1)),
    CONSTRAINT [refrig_flg_ck] CHECK ([refrig_flg]=(0) OR [refrig_flg]=(1)),
    CONSTRAINT [trlr_turn_flg_ck] CHECK ([turn_flg]=(0) OR [turn_flg]=(1))
);


GO
CREATE NONCLUSTERED INDEX [trlr_appt_id]
    ON [dbo].[trlr]([appt_id] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [trlr_loc_wh_stat]
    ON [dbo].[trlr]([stoloc] ASC, [stoloc_wh_id] ASC, [trlr_stat] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [trlr_yard_loc]
    ON [dbo].[trlr]([yard_loc] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [trlr_yard_loc_wh_id]
    ON [dbo].[trlr]([yard_loc_wh_id] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [trlr_trlr_num]
    ON [dbo].[trlr]([trlr_num] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [trlr_idx1]
    ON [dbo].[trlr]([yard_loc] ASC, [yard_loc_wh_id] ASC) WITH (FILLFACTOR = 90);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The Trailer table is used to represent receiving and shipping trailers in the system.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the trailer in the system. This value is generated by the system when the trailer is created.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Carrier for which this trailer transports inventory. A carrier code is only required for Shipping trailers.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'carcod';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'User identification for the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_num';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The trailer status is updated by system to indicate the current condition of trailer. Receiving trailer stat incl EX, CI, OR, R, SUSP. Shipping trailer statuses include CI, O, L, LDG, P, D, C', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_stat';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The Trailer Type is a user-defined value that can be assigned to the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_typ';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The size of the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_size';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Indicates that the trailer is a refrigerator trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'refrig_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Owner of the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_broker';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Identifier assigned to the first trailer seal.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_seal1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Identifier assigned to the second trailer seal.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_seal2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Identifier assigned to the third trailer seal.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_seal3';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Identifier assigned to the fourth trailer seal.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_seal4';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Shipment location. Logical location in the system where inventory for shipments are moved as the inventory is loaded on the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'stoloc';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Physical location in the yard where the trailer is located.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'yard_loc';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'User defined status that can be applied to the trailer to specify the current activity of that trailer. This status is a visual cue and is not associated with any DLx processes.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'yard_stat';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The weight of the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_wgt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The name of the trailer driver.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'driver_nam';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The drivers license number of the trailer driver.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'driver_lic_num';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Trailer closed date.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'close_dte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date the trailer is expected to be dispatched.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'pend_dte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date the trailer was dispatched or left the yard.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'dispatch_dte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Flags the trailer as having been automatically generated when the user chose to automatically generate the carrier move and stops.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'autogen_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Indicates that product on the trailer could be used to satisfy short allocations.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'hot_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Defines the trailer as either a Shipping or Receiving trailer. Trailer Code options are RCV or SHIP.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_cod';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Indicates whether this receiving trailer will be turned around for shipping', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'turn_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Indicates if this is a delivery trailer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'delv_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The appointment number assigned to the trailer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'appt_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Date trailer was arrived (checked in) into the facility', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'arrdte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Client ID (owner) of the trailer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'client_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'User identification for second trailer on the tractor if carrier move is part of pup.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'sec_trlr_num';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The tractor or cab number of the trailer, different than the customer known trailer number', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'tractor_num';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The condition of the trailer', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_cond';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Keeps track of whether or not the user is required to capture pallet positions for that trailer.  Currently will get set when the loader loads the first piece of inventory onto the trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'pal_slot_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The ID of the warehouse where the shipment location is.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'stoloc_wh_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'The ID of the warehouse where the yard location of the trailer is.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'yard_loc_wh_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Original Trailer Number.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'orig_trlr_num';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Trailer Reference number, will be used during trailer audit if user entered a reference number during trailer check in', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'trlr_ref';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Minimum Trailer Axle Position - The front most position (distance from the nose of trailer to center of the axles) that the trailer axle can be placed without an axle weight violation. This value is calculated and sent by PalletCtl.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'min_trlr_axle_pos';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Maximum Trailer Axle Position - The rear most position (distance from nose of trailer to center of axles) that the trailer axle can be placed without an axle weight violation.This value is calculated and sent by PalletCtl.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'max_trlr_axle_pos';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Front Axle Position - 5th Wheel Position, Distance from the nose of trailer to kingpin. This value is calculated and sent by PalletCtl.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'front_axle_pos';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Last date this trailer was modified.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'moddte';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Last user to modify this trailer.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'mod_usr_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Flag that identifies a trailer that is being loading in this moment.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'live_load_flg';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Safety Check Status - This column will store code values to indicate the current status of the trailer''s safety checks.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'trlr', @level2type = N'COLUMN', @level2name = N'safe_sts';

