CREATE TABLE [dbo].[unavail_sch_note] (
    [unavail_id] NVARCHAR (30) NOT NULL,
    [notlin]     NVARCHAR (4)  NOT NULL,
    [nottxt]     NVARCHAR (40) NULL,
    [edtflg]     INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [unavail_schnote_pk] PRIMARY KEY CLUSTERED ([unavail_id] ASC, [notlin] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [usnote_edtflg_ck] CHECK ([edtflg]=(0) OR [edtflg]=(1))
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Production Line Unavailable Schedule Notes.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'unavail_sch_note';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Unique identifier for the unavailable schedule in system. This value is generated by the system when the unavailable schedule is created. ', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'unavail_sch_note', @level2type = N'COLUMN', @level2name = N'unavail_id';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Note line.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'unavail_sch_note', @level2type = N'COLUMN', @level2name = N'notlin';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Note text.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'unavail_sch_note', @level2type = N'COLUMN', @level2name = N'nottxt';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Edit flag.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'unavail_sch_note', @level2type = N'COLUMN', @level2name = N'edtflg';

