CREATE TABLE [dbo].[salidas] (
    [id]                       BIGINT        IDENTITY (1, 1) NOT NULL,
    [operacion]                NVARCHAR (50) NOT NULL,
    [fecha_creacion]           DATETIME      NOT NULL,
    [fecha_modificacion]       DATETIME      NOT NULL,
    [client_id]                NVARCHAR (32) NOT NULL,
    [wh_id]                    NVARCHAR (32) NOT NULL,
    [ordnum]                   NVARCHAR (35) NOT NULL,
    [rmanum]                   NVARCHAR (30) NOT NULL,
    [ordtyp]                   NVARCHAR (4)  NOT NULL,
    [bus_grp]                  NVARCHAR (40) NOT NULL,
    [stcust]                   NVARCHAR (20) NOT NULL,
    [wave_flg]                 INT           NOT NULL,
    [adddte]                   DATETIME      NOT NULL,
    [moddte]                   DATETIME      NOT NULL,
    [mod_usr_id]               NVARCHAR (40) NOT NULL,
    [ordlin]                   NVARCHAR (10) NOT NULL,
    [prtnum]                   NVARCHAR (50) NOT NULL,
    [ordqty]                   INT           NOT NULL,
    [shpqty]                   INT           NOT NULL,
    [invsts_prg]               NVARCHAR (4)  NOT NULL,
    [ordlin_moddte]            DATETIME      NOT NULL,
    [ordlin_mod_usr_id]        NVARCHAR (40) NOT NULL,
    [lotnum]                   NVARCHAR (30) NOT NULL,
    [lotnum_last_upd_dt]       DATETIME      NOT NULL,
    [lotnum_last_upd_user_id]  NVARCHAR (40) NOT NULL,
    [shpsts]                   NVARCHAR (1)  NOT NULL,
    [shipment_loddte]          DATETIME      NOT NULL,
    [shipment_moddte]          DATETIME      NOT NULL,
    [shipment_mod_usr_id]      NVARCHAR (40) NOT NULL,
    [linsts]                   NVARCHAR (1)  NOT NULL,
    [shipment_line_stgqty]     INT           NOT NULL,
    [shipment_line_shpqty]     INT           NOT NULL,
    [shipment_line_moddte]     DATETIME      NOT NULL,
    [shipment_line_mod_usr_id] NVARCHAR (40) NOT NULL,
    CONSTRAINT [PK_salidas] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [UK_salidas_01] UNIQUE NONCLUSTERED ([client_id] ASC, [wh_id] ASC, [ordnum] ASC, [ordlin] ASC)
);

