create view dbo.invloc as 
 (select wh_id, arecod, stoloc, prtnum,
         prt_client_id, orgcod, revlvl, lotnum,
         sup_lotnum, mandte, expire_dte,
         inv_attr_str1, inv_attr_str2, inv_attr_str3,
         inv_attr_str4, inv_attr_str5, inv_attr_str6,
         inv_attr_str7, inv_attr_str8, inv_attr_str9,
         inv_attr_str10,inv_attr_str11,inv_attr_str12,
         inv_attr_str13,inv_attr_str14,inv_attr_str15,
         inv_attr_str16,inv_attr_str17,inv_attr_str18,
         inv_attr_int1, inv_attr_int2, inv_attr_int3,
         inv_attr_int4, inv_attr_int5, inv_attr_flt1,
         inv_attr_flt2, inv_attr_flt3, inv_attr_dte1,
         inv_attr_dte2, invsts, untpak, untcas, 0 untpal,
         sum(untqty) untqty,
         min(olddte) olddte,
         max(newdte) newdte,
         min(expire_dte) old_expire_dte,
         max(expire_dte) new_expire_dte,
         sum(comqty) comqty,
         sum(com_catch_qty) com_catch_qty,
         sum(pndqty) pndqty,
         rttn_id,
         alcflg
    from invloc_view
   group by wh_id, arecod, stoloc, prtnum,
            prt_client_id, orgcod, revlvl, lotnum,
            sup_lotnum, mandte, expire_dte,
            inv_attr_str1, inv_attr_str2, inv_attr_str3,
            inv_attr_str4, inv_attr_str5, inv_attr_str6,
            inv_attr_str7, inv_attr_str8, inv_attr_str9,
            inv_attr_str10,inv_attr_str11,inv_attr_str12,
            inv_attr_str13,inv_attr_str14,inv_attr_str15,
            inv_attr_str16,inv_attr_str17,inv_attr_str18,
            inv_attr_int1, inv_attr_int2, inv_attr_int3,
            inv_attr_int4, inv_attr_int5, inv_attr_flt1,
            inv_attr_flt2, inv_attr_flt3, inv_attr_dte1,
            inv_attr_dte2, invsts, untpak, untcas,
            rttn_id, alcflg)