create view dbo.pckwrk_view as 
 select pckwrk_hdr.*,
        pckwrk_dtl.wrkref_dtl,
        pckwrk_dtl.pckqty dtl_pckqty,
        pckwrk_dtl.pck_catch_qty dtl_pck_catch_qty,
        pckwrk_dtl.appqty dtl_appqty,
        pckwrk_dtl.app_catch_qty dtl_app_catch_qty,
        pckwrk_dtl.cmbcod,
        pckwrk_dtl.dstloc,
        pckwrk_dtl.dstare,
        pckwrk_dtl.ship_line_id,
        pckwrk_dtl.ship_id,
        pckwrk_dtl.ordnum,
        pckwrk_dtl.ordlin,
        pckwrk_dtl.ordsln,
        pckwrk_dtl.stcust,
        pckwrk_dtl.rtcust,
        pckwrk_dtl.concod,
        pckwrk_dtl.ship_ctncod,
        pckwrk_dtl.ship_ctnnum,
        pckwrk_dtl.wkonum,
        pckwrk_dtl.wkorev,
        pckwrk_dtl.wkolin,
        pckwrk_dtl.subnum,
        pckwrk_dtl.dtlnum,
        pckwrk_dtl.subucc,
        pckwrk_dtl.subtag,
        pckwrk_dtl.cur_cas,
        pckwrk_dtl.tot_cas_cnt,
        pckwrk_dtl.bto_seqnum,
        pckwrk_dtl.slot,
        pckwrk_dtl.bto_dlv_seq,
        pckwrk_dtl.pm_err_cod,
        pckwrk_dtl.pm_err_desc,
        pckwrk_dtl.ctnerr_flg
   from pckwrk_hdr,
        pckwrk_dtl
  where pckwrk_dtl.wrkref = pckwrk_hdr.wrkref