create view dbo.ship_struct_view as 
    select h.ship_id,
	         h.wh_id,
	         h.host_client_id,
	         h.host_ext_id,
	         h.shpsts,
	         h.stop_id,
	         h.rt_adr_id,
	         h.cargrp,
	         h.carcod,
	         h.srvlvl,
	         h.sddflg,
	         h.doc_num,
	         h.track_num,
	         h.mst_waybill,
	         h.frtchg,
	         h.frtcod,
           h.frtrte,
	         h.adddte,
	         h.alcdte,
	         h.stgdte,
	         h.loddte,
	         h.entdte,
	         h.early_shpdte,
	         h.late_shpdte,
           h.early_dlvdte,
	         h.late_dlvdte,
	         h.dstare,
	         h.dstloc,
	         h.rrlflg,
           h.wave_set,
           h.tms_group_id,
           h.lst_prtdte,
           h.super_ship_id,
           h.super_ship_flg,
           h.in_transit_flg,
           h.pln_shpsts,
           h.ses_grp_nam,
           h.optm_base_cost,
           h.rate_serv_nam,
           h.arcdte,
           h.arc_src,
           h.lbl_prtdte,
           h.ses_tag,
           h.price_sts,
           h.src_sys,
           h.par_ship_id,
           h.hub_adr_id,
           h.hub_arrdte,
           h.zs_line_haul_id,
           h.hub_rate_serv_nam,
           h.tot_pkg_qty,
           h.crncy_code,
           h.aesitn,
           h.ftsrnum,
           h.export_typ,
           h.docind,
           h.descgoods,
           h.exprsntxt,
           h.pack_code,
           h.pln_cmpl_flg,
           h.dispatch_code,
           h.moddte,
           h.mod_usr_id,
           h.book_num,
           stp.stop_nam,
           stp.stop_seq,
           stp.car_move_id,
           stp.adr_id,
           stp.stop_cmpl_flg,
           stp.stop_seal,
           cm.trlr_id,
           cm.tms_load_id,
           cm.trans_mode,
           tl.trlr_num,
           tl.trlr_stat,
           tl.trlr_typ,
           tl.trlr_size,
           tl.refrig_flg,
           tl.trlr_broker,
           tl.trlr_seal1,
           tl.trlr_seal2,
           tl.trlr_seal3,
           tl.trlr_seal4,
           tl.stoloc,
           tl.yard_loc,
           tl.yard_stat,
           tl.trlr_wgt,
           tl.driver_nam,
           tl.driver_lic_num,
           tl.close_dte,
           tl.pend_dte,
           tl.dispatch_dte,
           tl.autogen_flg,
           tl.turn_flg,
           tl.arrdte,
           tl.tractor_num,
           tl.trlr_cond,
           tl.trlr_cod,
           tl.hot_flg,
           coalesce(tl.appt_id, a.appt_id) appt_id,
           tl.safe_sts
      from shipment h
      left outer join stop stp 
        on stp.stop_id = h.stop_id 
      left outer join car_move cm 
        on cm.car_move_id = stp.car_move_id 
      left outer join trlr tl 
        on tl.trlr_id = cm.trlr_id 
      left outer join appt a
        on cm.car_move_id = a.car_move_id