CREATE TABLE [dbo].[mensajes_abastecimientos_gws] (
    [id_mensaje]               BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_orden_recibo]          BIGINT        NOT NULL,
    [estado]                   VARCHAR (50)  NOT NULL,
    [fecha_envio]              DATETIME2 (0) NULL,
    [fecha_confirmacion_envio] DATETIME2 (0) NULL,
    [DocDate]                  VARCHAR (10)  NULL,
    [DueDate]                  VARCHAR (10)  NOT NULL,
    [CardCode]                 VARCHAR (20)  NOT NULL,
    [Series]                   VARCHAR (20)  NOT NULL,
    [FromWarehouse]            VARCHAR (50)  NOT NULL,
    [TaxDate]                  VARCHAR (10)  NULL,
    [Address]                  VARCHAR (150) NOT NULL,
    [Comments]                 VARCHAR (150) NOT NULL,
    [DocObjectCode]            INT           NOT NULL,
    [U_BKV_UID]                VARCHAR (20)  NOT NULL,
    [U_GW_Fecha1]              VARCHAR (10)  NOT NULL,
    [U_GW_Fecha2]              VARCHAR (10)  NOT NULL,
    [U_Ocompra]                VARCHAR (50)  NOT NULL,
    [U_GW_PRE_DOC_ORG]         VARCHAR (20)  NOT NULL,
    [U_GW_NU_DOC_ORG]          VARCHAR (50)  NOT NULL,
    [U_GW_PRE_DOC_ANT]         VARCHAR (20)  NOT NULL,
    [U_GW_NU_DOC_ANT]          VARCHAR (50)  NOT NULL,
    [version]                  INT           NOT NULL,
    [usuario_creacion]         VARCHAR (50)  NOT NULL,
    [fecha_creacion]           DATETIME2 (0) NOT NULL,
    [usuario_modificacion]     VARCHAR (50)  NOT NULL,
    [fecha_modificacion]       DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_mensajes_abastecimientos_gws] PRIMARY KEY CLUSTERED ([id_mensaje] ASC) WITH (FILLFACTOR = 80)
);

