


CREATE VIEW [dbo].[tarifas_gws_maq] AS 
SELECT 'GWS0' AS DEPT_CODE, 226 AS OFERTA, 274 AS ESTAMPILLA UNION
SELECT 'GWS1' AS DEPT_CODE, 37 AS OFERTA, 87 AS ESTAMPILLA UNION
SELECT 'GWS10' AS DEPT_CODE, 1164 AS OFERTA, NULL AS ESTAMPILLA UNION
SELECT 'GWS11' AS DEPT_CODE, 37 AS OFERTA, 55 AS ESTAMPILLA UNION
SELECT 'GWS12' AS DEPT_CODE, NULL AS OFERTA, 274 AS ESTAMPILLA UNION
SELECT 'GWS13' AS DEPT_CODE, NULL AS OFERTA, 87 AS ESTAMPILLA UNION
SELECT 'GWS14' AS DEPT_CODE, NULL AS OFERTA, 55 AS ESTAMPILLA UNION
SELECT 'GWS15' AS DEPT_CODE, 226 AS OFERTA, 274 AS ESTAMPILLA UNION
SELECT 'GWS16' AS DEPT_CODE, 37 AS OFERTA, 87 AS ESTAMPILLA UNION
SELECT 'GWS17' AS DEPT_CODE, 37 AS OFERTA, 55 AS ESTAMPILLA UNION
SELECT 'GWS18' AS DEPT_CODE, 37 AS OFERTA, 87 AS ESTAMPILLA UNION
SELECT 'GWS19' AS DEPT_CODE, 37 AS OFERTA, 55 AS ESTAMPILLA UNION
SELECT 'GWS2' AS DEPT_CODE, 37 AS OFERTA, 55 AS ESTAMPILLA UNION
SELECT 'GWS20' AS DEPT_CODE, 74 AS OFERTA, 55 AS ESTAMPILLA UNION 
SELECT 'GWS21' AS DEPT_CODE, 452 AS OFERTA, 274 AS ESTAMPILLA UNION 
SELECT 'GWS22' AS DEPT_CODE, 74  AS OFERTA, 55  AS ESTAMPILLA UNION 
SELECT 'GWS3' AS DEPT_CODE, 37 AS OFERTA, 274 AS ESTAMPILLA UNION
SELECT 'GWS4' AS DEPT_CODE, 37 AS OFERTA, 87 AS ESTAMPILLA UNION
SELECT 'GWS5' AS DEPT_CODE, 302 AS OFERTA, NULL AS ESTAMPILLA UNION
SELECT 'GWS6' AS DEPT_CODE, 1091 AS OFERTA, NULL AS ESTAMPILLA UNION
SELECT 'GWS7' AS DEPT_CODE, 478 AS OFERTA, NULL AS ESTAMPILLA UNION
SELECT 'GWS8' AS DEPT_CODE, 979 AS OFERTA, NULL AS ESTAMPILLA UNION
SELECT 'GWS9' AS DEPT_CODE, 1035 AS OFERTA, NULL AS ESTAMPILLA UNION
SELECT 'AGUA' AS DEPT_CODE, 37 AS OFERTA, NULL AS ESTAMPILLA