


CREATE VIEW [dbo].[tarifas_heinz_maq] AS 
SELECT 'HNZ01' AS DEPT_CODE, 105 AS OFERTA UNION
SELECT 'HNZ02' AS DEPT_CODE, 51 AS OFERTA UNION
SELECT 'HNZ03' AS DEPT_CODE, 827 AS OFERTA UNION
SELECT 'HNZ04' AS DEPT_CODE, 105 AS OFERTA UNION
SELECT 'HNZ05' AS DEPT_CODE, 240 AS OFERTA UNION
SELECT 'HNZ06' AS DEPT_CODE, 248 AS OFERTA UNION
SELECT 'HNZ07' AS DEPT_CODE, 90 AS OFERTA UNION
SELECT 'HNZ08' AS DEPT_CODE, 309 AS OFERTA UNION
SELECT 'HNZ09' AS DEPT_CODE, 827 AS OFERTA UNION
SELECT 'HNZ10' AS DEPT_CODE, 309 AS OFERTA UNION
SELECT 'HNZ11' AS DEPT_CODE, 24 AS OFERTA UNION
SELECT 'HNZ12' AS DEPT_CODE, 63 AS OFERTA UNION
SELECT 'HNZ13' AS DEPT_CODE, 163 AS OFERTA UNION
SELECT 'HNZ14' AS DEPT_CODE, 257 AS OFERTA UNION
SELECT 'HNZ15' AS DEPT_CODE, 38 AS OFERTA UNION
SELECT 'HNZ16' AS DEPT_CODE, 87 AS OFERTA UNION
SELECT 'HNZ17' AS DEPT_CODE, 64 AS OFERTA UNION
SELECT 'HNZ18' AS DEPT_CODE, 14 AS OFERTA UNION
SELECT 'HNZ19' AS DEPT_CODE, 248 AS OFERTA UNION
SELECT 'HNZ20' AS DEPT_CODE, 45 AS OFERTA