CREATE TABLE [dbo].[____preordenes_salida] (
    [id_preorden_salida]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_preorden_venta]           BIGINT        NOT NULL,
    [id_tipo_documento]           VARCHAR (20)  NOT NULL,
    [numero_preorden_salida]      VARCHAR (20)  NOT NULL,
    [estado]                      VARCHAR (50)  NOT NULL,
    [id_bodega]                   BIGINT        NOT NULL,
    [id_linea_negocio]            BIGINT        NULL,
    [id_tipo_ruta]                BIGINT        NULL,
    [id_tipo_vehiculo]            BIGINT        NULL,
    [id_corte_preordenes_salidas] BIGINT        NULL,
    [prioridad]                   INT           NULL,
    [id_orden]                    BIGINT        NULL,
    [autorizado_identificacion]   VARCHAR (20)  NOT NULL,
    [autorizado_nombres]          VARCHAR (100) NOT NULL,
    [fecha_minima_solicitada]     DATE          NULL,
    [fecha_maxima_solicitada]     DATE          NULL,
    [hora_minima_solicitada]      TIME (0)      NULL,
    [hora_maxima_solicitada]      TIME (0)      NULL,
    [requiere_transporte]         VARCHAR (1)   NOT NULL,
    [requiere_recaudo]            VARCHAR (1)   NOT NULL,
    [requiere_agendamiento]       VARCHAR (1)   NOT NULL,
    [nota]                        VARCHAR (200) NOT NULL,
    [version]                     INT           NOT NULL,
    [usuario_creacion]            VARCHAR (50)  NOT NULL,
    [fecha_creacion]              DATETIME2 (0) NOT NULL,
    [usuario_modificacion]        VARCHAR (50)  NOT NULL,
    [fecha_modificacion]          DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_preordenes_salida] PRIMARY KEY CLUSTERED ([id_preorden_salida] ASC) WITH (FILLFACTOR = 80)
);

