CREATE TABLE [dbo].[__remesas_transporte] (
    [id_remesa_transporte]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_orden_transporte]           BIGINT        NOT NULL,
    [id_tipo_documento]             VARCHAR (20)  NOT NULL,
    [numero_documento]              VARCHAR (20)  NOT NULL,
    [prefijo]                       VARCHAR (20)  NOT NULL,
    [numero_documento_sin_prefijo]  VARCHAR (20)  NOT NULL,
    [estado]                        VARCHAR (50)  NOT NULL,
    [id_bodega]                     BIGINT        NOT NULL,
    [id_cliente]                    BIGINT        NOT NULL,
    [id_servicio]                   BIGINT        NOT NULL,
    [id_canal]                      BIGINT        NULL,
    [id_linea_negocio]              BIGINT        NOT NULL,
    [id_tipo_ruta]                  BIGINT        NOT NULL,
    [id_tipo_vehiculo]              BIGINT        NOT NULL,
    [id_tipo_tarifa]                BIGINT        NOT NULL,
    [id_tipo_flete]                 BIGINT        NOT NULL,
    [placa]                         VARCHAR (20)  NOT NULL,
    [id_direccion_remitente]        BIGINT        NOT NULL,
    [id_ciudad_remitente]           BIGINT        NOT NULL,
    [remitente_direccion]           VARCHAR (150) NOT NULL,
    [remitente_tipo_documento]      VARCHAR (20)  NOT NULL,
    [remitente_numero_documento]    VARCHAR (20)  NOT NULL,
    [remitente_nombre]              VARCHAR (100) NOT NULL,
    [remitente_telefonos]           VARCHAR (100) NOT NULL,
    [remitente_contacto]            VARCHAR (100) NOT NULL,
    [id_direccion_destinatario]     BIGINT        NOT NULL,
    [id_ciudad_destinatario]        BIGINT        NOT NULL,
    [destinatario_direccion]        VARCHAR (150) NOT NULL,
    [destinatario_tipo_documento]   VARCHAR (20)  NOT NULL,
    [destinatario_numero_documento] VARCHAR (20)  NOT NULL,
    [destinatario_nombre]           VARCHAR (100) NOT NULL,
    [destinatario_telefonos]        VARCHAR (100) NOT NULL,
    [destinatario_contacto]         VARCHAR (100) NOT NULL,
    [fecha_hora_compromiso]         DATE          NOT NULL,
    [hora_cita_minima]              TIME (0)      NOT NULL,
    [hora_cita_maxima]              TIME (0)      NOT NULL,
    [fecha_hora_llegada]            DATETIME2 (0) NOT NULL,
    [fecha_hora_inicio_visita]      DATETIME2 (0) NOT NULL,
    [fecha_hora_fin_visita]         DATETIME2 (0) NOT NULL,
    [requiere_reprogramacion]       VARCHAR (1)   NOT NULL,
    [requiere_cita_reprogramacion]  VARCHAR (1)   NOT NULL,
    [fecha_reprogramada]            DATE          NULL,
    [hora_minima_reprogramada]      TIME (0)      NULL,
    [hora_maxima_reprogramada]      TIME (0)      NULL,
    [id_causal_novedad]             BIGINT        NULL,
    [nota_novedad]                  VARCHAR (200) NOT NULL,
    [id_responsable_novedad]        BIGINT        NULL,
    [nota_cierre]                   VARCHAR (200) NOT NULL,
    [usuario_cierre]                VARCHAR (50)  NOT NULL,
    [fecha_cierre]                  DATETIME2 (0) NULL,
    [version]                       INT           NOT NULL,
    [usuario_creacion]              VARCHAR (50)  NOT NULL,
    [fecha_creacion]                DATETIME2 (0) NOT NULL,
    [usuario_modificacion]          VARCHAR (50)  NOT NULL,
    [fecha_modificacion]            DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_remesas_transporte] PRIMARY KEY CLUSTERED ([id_remesa_transporte] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_remesas_transporte_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_remesas_transporte_canales] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[canales] ([id_canal]),
    CONSTRAINT [FK_remesas_transporte_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_remesas_transporte_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_remesas_transporte_tipos_identificacion] FOREIGN KEY ([id_tipo_documento]) REFERENCES [dbo].[tipos_identificacion] ([id_tipo_identificacion])
);

