CREATE TABLE [dbo].[ordenes_alistamiento] (
    [id_orden_alistamiento]       BIGINT        NOT NULL,
    [id_solicitud]                BIGINT        NOT NULL,
    [estado_orden]                VARCHAR (50)  NOT NULL,
    [numero_orden]                VARCHAR (35)  NOT NULL,
    [id_cliente]                  BIGINT        NOT NULL,
    [id_servicio]                 BIGINT        NOT NULL,
    [id_tipo_orden_wms]           BIGINT        NULL,
    [id_bodega]                   BIGINT        NOT NULL,
    [id_tercero]                  BIGINT        NULL,
    [tercero_identificacion]      VARCHAR (20)  NOT NULL,
    [tercero_nombre]              VARCHAR (100) NOT NULL,
    [id_canal]                    BIGINT        NULL,
    [fecha_minima_solicitada]     DATE          NOT NULL,
    [fecha_maxima_solicitada]     DATE          NOT NULL,
    [requiere_transporte]         BIT           NOT NULL,
    [id_ciudad_destinatario]      BIGINT        NULL,
    [direccion_destinatario]      VARCHAR (150) NOT NULL,
    [nota]                        VARCHAR (200) NOT NULL,
    [fecha_confirmacion_creacion] DATETIME2 (0) NULL,
    [fecha_confirmacion_stage]    DATETIME2 (0) NULL,
    [version]                     INT           CONSTRAINT [DF__tmp_ms_xx__versi__7913E27D] DEFAULT ((0)) NOT NULL,
    [usuario_creacion]            VARCHAR (50)  NOT NULL,
    [fecha_creacion]              DATETIME2 (0) NOT NULL,
    [usuario_modificacion]        VARCHAR (50)  NOT NULL,
    [fecha_modificacion]          DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_ordenes_alistamiento] PRIMARY KEY CLUSTERED ([id_orden_alistamiento] ASC),
    CONSTRAINT [FK_ordenes_alistamiento_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_ordenes_alistamiento_canales] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[canales] ([id_canal]),
    CONSTRAINT [FK_ordenes_alistamiento_ciudades] FOREIGN KEY ([id_ciudad_destinatario]) REFERENCES [dbo].[ciudades] ([id_ciudad]),
    CONSTRAINT [FK_ordenes_alistamiento_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_ordenes_alistamiento_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_ordenes_alistamiento_solicitudes] FOREIGN KEY ([id_solicitud]) REFERENCES [dbo].[solicitudes] ([id_solicitud]),
    CONSTRAINT [FK_ordenes_alistamiento_terceros] FOREIGN KEY ([id_tercero]) REFERENCES [dbo].[terceros] ([id_tercero]),
    CONSTRAINT [UK_ordenes_alistamiento_01] UNIQUE NONCLUSTERED ([id_cliente] ASC, [numero_orden] ASC)
);




