CREATE TABLE [dbo].[ordenes_recibo] (
    [id_orden_recibo]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_orden]                BIGINT        NOT NULL,
    [estado]                  VARCHAR (50)  NOT NULL,
    [id_bodega]               BIGINT        NOT NULL,
    [id_cliente]              BIGINT        NOT NULL,
    [id_servicio]             BIGINT        NOT NULL,
    [id_tercero]              BIGINT        NULL,
    [tercero_codigo_alterno]  VARCHAR (20)  NOT NULL,
    [tercero_nombre]          VARCHAR (100) NOT NULL,
    [id_linea_negocio]        BIGINT        NOT NULL,
    [fecha_minima_solicitada] DATE          NULL,
    [fecha_maxima_solicitada] DATE          NULL,
    [fecha_cita]              DATE          NULL,
    [hora_cita_minima]        TIME (0)      NULL,
    [hora_cita_maxima]        TIME (0)      NULL,
    [client_id]               NVARCHAR (32) NOT NULL,
    [invtyp]                  NVARCHAR (4)  NOT NULL,
    [invnum]                  NVARCHAR (35) NOT NULL,
    [wh_id]                   NVARCHAR (32) NOT NULL,
    [supnum]                  NVARCHAR (32) NOT NULL,
    [invdte]                  DATETIME      NOT NULL,
    [moddte]                  DATETIME      NOT NULL,
    [mod_usr_id]              NVARCHAR (40) NOT NULL,
    [nota_cierre]             VARCHAR (200) NOT NULL,
    [usuario_cierre]          VARCHAR (50)  NOT NULL,
    [fecha_cierre]            DATETIME2 (0) NULL,
    [id_causal_anulacion]     BIGINT        NULL,
    [nota_anulacion]          VARCHAR (200) NOT NULL,
    [usuario_anulacion]       VARCHAR (50)  NOT NULL,
    [fecha_anulacion]         DATETIME2 (0) NULL,
    [version]                 INT           NOT NULL,
    [usuario_creacion]        VARCHAR (50)  NOT NULL,
    [fecha_creacion]          DATETIME2 (0) NOT NULL,
    [usuario_modificacion]    VARCHAR (50)  NOT NULL,
    [fecha_modificacion]      DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_ordenes_recibo] PRIMARY KEY CLUSTERED ([id_orden_recibo] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ordenes_recibo_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_ordenes_recibo_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_ordenes_recibo_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_ordenes_recibo_terceros] FOREIGN KEY ([id_tercero]) REFERENCES [dbo].[terceros] ([id_tercero])
);

