CREATE TABLE [dbo].[ordenes_transporte] (
    [id_orden_transporte]                 BIGINT           NOT NULL,
    [id_solicitud]                        BIGINT           NOT NULL,
    [estado_orden]                        VARCHAR (50)     NOT NULL,
    [numero_orden]                        VARCHAR (20)     NOT NULL,
    [numero_orden_wms]                    VARCHAR (50)     NOT NULL,
    [numero_remesa]                       VARCHAR (50)     NULL,
    [numero_confirmacion_tms]             VARCHAR (50)     NULL,
    [numero_remesa_tms]                   VARCHAR (50)     NULL,
    [id_cliente]                          BIGINT           NOT NULL,
    [id_servicio]                         BIGINT           NOT NULL,
    [id_bodega]                           BIGINT           NOT NULL,
    [id_canal]                            BIGINT           NULL,
    [id_tipo_remesa]                      BIGINT           NOT NULL,
    [placa]                               VARCHAR (20)     NOT NULL,
    [secuencia_ruta]                      INT              NOT NULL,
    [id_ciudad_remitente]                 BIGINT           NOT NULL,
    [remitente_direccion]                 VARCHAR (150)    NOT NULL,
    [id_direccion_remitente]              BIGINT           NULL,
    [remitente_cx]                        DECIMAL (18, 15) NULL,
    [remitente_cy]                        DECIMAL (18, 15) NULL,
    [id_tipo_identificacion_remitente]    VARCHAR (20)     NOT NULL,
    [remitente_identificacion]            VARCHAR (20)     NOT NULL,
    [remitente_nombre]                    VARCHAR (100)    NOT NULL,
    [remitente_telefonos]                 VARCHAR (100)    NOT NULL,
    [remitente_contacto]                  VARCHAR (100)    NOT NULL,
    [id_ciudad_destinatario]              BIGINT           NOT NULL,
    [destinatario_direccion]              VARCHAR (150)    NOT NULL,
    [id_direccion_destinatario]           BIGINT           NULL,
    [destinatario_cx]                     DECIMAL (18, 15) NULL,
    [destinatario_cy]                     DECIMAL (18, 15) NULL,
    [id_tipo_identificacion_destinatario] VARCHAR (20)     NOT NULL,
    [destinatario_identificacion]         VARCHAR (20)     NOT NULL,
    [destinatario_nombre]                 VARCHAR (100)    NOT NULL,
    [destinatario_telefonos]              VARCHAR (100)    NOT NULL,
    [destinatario_contacto]               VARCHAR (100)    NOT NULL,
    [fecha_minima_solicitada]             DATE             NOT NULL,
    [fecha_maxima_solicitada]             DATE             NOT NULL,
    [hora_minima_solicitada]              TIME (0)         NOT NULL,
    [hora_maxima_solicitada]              TIME (0)         NOT NULL,
    [fecha_cita]                          DATE             NULL,
    [hora_cita_minima]                    TIME (0)         NULL,
    [hora_cita_maxima]                    TIME (0)         NULL,
    [fecha_hora_llegada]                  DATETIME2 (0)    NULL,
    [fecha_hora_inicio_visita]            DATETIME2 (0)    NULL,
    [fecha_hora_fin_visita]               DATETIME2 (0)    NULL,
    [id_causal_novedad]                   BIGINT           NULL,
    [nota_novedad]                        VARCHAR (200)    NOT NULL,
    [id_responsable_novedad]              BIGINT           NULL,
    [version]                             INT              NOT NULL,
    [usuario_creacion]                    VARCHAR (50)     NOT NULL,
    [fecha_creacion]                      DATETIME2 (0)    NOT NULL,
    [usuario_modificacion]                VARCHAR (50)     NOT NULL,
    [fecha_modificacion]                  DATETIME2 (0)    NOT NULL,
    CONSTRAINT [PK_ordenes_transporte] PRIMARY KEY CLUSTERED ([id_orden_transporte] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ordenes_transporte_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_ordenes_transporte_canales] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[canales] ([id_canal]),
    CONSTRAINT [FK_ordenes_transporte_ciudades_destinatario] FOREIGN KEY ([id_ciudad_destinatario]) REFERENCES [dbo].[ciudades] ([id_ciudad]),
    CONSTRAINT [FK_ordenes_transporte_ciudades_remitente] FOREIGN KEY ([id_ciudad_remitente]) REFERENCES [dbo].[ciudades] ([id_ciudad]),
    CONSTRAINT [FK_ordenes_transporte_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_ordenes_transporte_direcciones_destinatario] FOREIGN KEY ([id_direccion_destinatario]) REFERENCES [dbo].[direcciones] ([id_direccion]),
    CONSTRAINT [FK_ordenes_transporte_direcciones_remitente] FOREIGN KEY ([id_direccion_remitente]) REFERENCES [dbo].[direcciones] ([id_direccion]),
    CONSTRAINT [FK_ordenes_transporte_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_ordenes_transporte_solicitudes] FOREIGN KEY ([id_solicitud]) REFERENCES [dbo].[solicitudes] ([id_solicitud]),
    CONSTRAINT [FK_ordenes_transporte_tipos_identificacion_destinatario] FOREIGN KEY ([id_tipo_identificacion_destinatario]) REFERENCES [dbo].[tipos_identificacion] ([id_tipo_identificacion]),
    CONSTRAINT [FK_ordenes_transporte_tipos_identificacion_remitente] FOREIGN KEY ([id_tipo_identificacion_remitente]) REFERENCES [dbo].[tipos_identificacion] ([id_tipo_identificacion]),
    CONSTRAINT [FK_ordenes_transporte_tipos_remesa] FOREIGN KEY ([id_tipo_remesa]) REFERENCES [dbo].[tipos_remesa] ([id_tipo_remesa])
);



