CREATE TABLE [dbo].[ordenes_manufactura] (
    [id_orden_manufactura]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [id_orden]                BIGINT          NOT NULL,
    [estado]                  VARCHAR (50)    NOT NULL,
    [id_bodega]               BIGINT          NOT NULL,
    [id_cliente]              BIGINT          NOT NULL,
    [id_servicio]             BIGINT          NOT NULL,
    [id_linea_negocio]        BIGINT          NOT NULL,
    [fecha_minima_solicitada] DATE            NULL,
    [fecha_maxima_solicitada] DATE            NULL,
    [client_id]               NVARCHAR (32)   NOT NULL,
    [wko_typ]                 VARCHAR (32)    NOT NULL,
    [wkorev]                  NVARCHAR (4000) NOT NULL,
    [wh_id]                   NVARCHAR (32)   NOT NULL,
    [prcpri]                  VARCHAR (1)     NOT NULL,
    [prd_tol_pct]             VARCHAR (1)     NOT NULL,
    [prcare]                  VARCHAR (3)     NOT NULL,
    [prdlin]                  VARCHAR (5)     NOT NULL,
    [moddte]                  DATETIME        NULL,
    [mod_usr_id]              NVARCHAR (40)   NULL,
    [nota_cierre]             VARCHAR (200)   NOT NULL,
    [usuario_cierre]          VARCHAR (50)    NOT NULL,
    [fecha_cierre]            DATETIME2 (0)   NULL,
    [id_causal_anulacion]     BIGINT          NULL,
    [nota_anulacion]          VARCHAR (200)   NOT NULL,
    [usuario_anulacion]       VARCHAR (50)    NOT NULL,
    [fecha_anulacion]         DATETIME2 (0)   NULL,
    [version]                 INT             NOT NULL,
    [usuario_creacion]        VARCHAR (50)    NOT NULL,
    [fecha_creacion]          DATETIME2 (0)   NOT NULL,
    [usuario_modificacion]    VARCHAR (50)    NOT NULL,
    [fecha_modificacion]      DATETIME2 (0)   NOT NULL,
    CONSTRAINT [PK_ordenes_manufactura] PRIMARY KEY CLUSTERED ([id_orden_manufactura] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ordenes_manufactura_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_ordenes_manufactura_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_ordenes_manufactura_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio])
);

