CREATE TABLE [dbo].[ordenes_transporte] (
    [id_orden_transporte]                BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_orden]                           BIGINT        NOT NULL,
    [id_tipo_documento]                  VARCHAR (20)  NOT NULL,
    [numero_documento]                   VARCHAR (20)  NOT NULL,
    [prefijo]                            VARCHAR (20)  NOT NULL,
    [numero_documento_sin_prefijo]       VARCHAR (20)  NOT NULL,
    [estado]                             VARCHAR (50)  NOT NULL,
    [id_bodega]                          BIGINT        NOT NULL,
    [id_cliente]                         BIGINT        NOT NULL,
    [id_servicio]                        BIGINT        NOT NULL,
    [id_tercero]                         BIGINT        NULL,
    [tercero_codigo_alterno]             VARCHAR (20)  NOT NULL,
    [tercero_nombre]                     VARCHAR (100) NOT NULL,
    [id_canal]                           BIGINT        NULL,
    [id_linea_negocio]                   BIGINT        NULL,
    [id_tipo_ruta]                       BIGINT        NULL,
    [id_tipo_vehiculo]                   BIGINT        NULL,
    [id_ciudad_remitente]                BIGINT        NOT NULL,
    [ciudad_remitente_codigo_alterno]    VARCHAR (50)  NOT NULL,
    [direccion_remitente]                VARCHAR (150) NOT NULL,
    [id_direccion_remitente]             BIGINT        NULL,
    [id_punto_remitente]                 BIGINT        NULL,
    [punto_remitente_codigo_alterno]     VARCHAR (50)  NOT NULL,
    [punto_remitente_nombre]             VARCHAR (100) NOT NULL,
    [requiere_cita_remitente]            VARCHAR (1)   NOT NULL,
    [fecha_cita_remitente]               DATE          NULL,
    [hora_cita_minima_remitente]         TIME (0)      NULL,
    [hora_cita_maxima_remitente]         TIME (0)      NULL,
    [id_ciudad_destinatario]             BIGINT        NOT NULL,
    [ciudad_destinatario_codigo_alterno] VARCHAR (50)  NOT NULL,
    [direccion_destinatario]             VARCHAR (150) NOT NULL,
    [id_direccion_destinatario]          BIGINT        NULL,
    [id_punto_destinatario]              BIGINT        NULL,
    [punto_destinatario_codigo_alterno]  VARCHAR (50)  NOT NULL,
    [punto_destinatario_nombre]          VARCHAR (100) NOT NULL,
    [requiere_cita_destinatario]         VARCHAR (1)   NOT NULL,
    [fecha_cita_destinatario]            DATE          NULL,
    [hora_cita_minima_destinatario]      TIME (0)      NULL,
    [hora_cita_maxima_destinatario]      TIME (0)      NULL,
    [id_causal_anulacion]                BIGINT        NULL,
    [nota_anulacion]                     VARCHAR (200) NOT NULL,
    [usuario_anulacion]                  VARCHAR (50)  NOT NULL,
    [fecha_anulacion]                    DATETIME2 (0) NULL,
    [version]                            INT           NOT NULL,
    [usuario_creacion]                   VARCHAR (50)  NOT NULL,
    [fecha_creacion]                     DATETIME2 (0) NOT NULL,
    [usuario_modificacion]               VARCHAR (50)  NOT NULL,
    [fecha_modificacion]                 DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_ordenes_transporte] PRIMARY KEY CLUSTERED ([id_orden_transporte] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_ordenes_transporte_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_ordenes_transporte_canales] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[canales] ([id_canal]),
    CONSTRAINT [FK_ordenes_transporte_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_ordenes_transporte_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_ordenes_transporte_terceros] FOREIGN KEY ([id_tercero]) REFERENCES [dbo].[terceros] ([id_tercero]),
    CONSTRAINT [FK_ordenes_transporte_tipos_identificacion] FOREIGN KEY ([id_tipo_documento]) REFERENCES [dbo].[tipos_identificacion] ([id_tipo_identificacion])
);

