CREATE TABLE [dbo].[solicitudes_actas_ingredion] (
    [id_solicitud_acta]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [integracion]                   VARCHAR (50)  NOT NULL,
    [correlacion]                   VARCHAR (100) NOT NULL,
    [id_externo]                    VARCHAR (100) NOT NULL,
    [tipo_solicitud]                VARCHAR (50)  NOT NULL,
    [estado_solicitud]              VARCHAR (50)  NOT NULL,
    [subestado_solicitud]           VARCHAR (50)  NOT NULL,
    [reintentos]                    INT           CONSTRAINT [DF_solicitudes_actas_ingredion_reintentos] DEFAULT ((0)) NULL,
    [numero_confirmacion_silogtran] VARCHAR (50)  NULL,
    [fecha_integracion_silogtran]   DATETIME2 (0) NULL,
    [numero_solicitud]              VARCHAR (20)  NOT NULL,
    [id_cliente]                    BIGINT        NOT NULL,
    [id_servicio]                   BIGINT        NOT NULL,
    [servicio_codigo_alterno]       VARCHAR (50)  NOT NULL,
    [id_bodega]                     BIGINT        NOT NULL,
    [bodega_codigo_alterno]         VARCHAR (50)  NOT NULL,
    [tercero_identificacion]        VARCHAR (20)  NOT NULL,
    [tercero_nombre]                VARCHAR (150) NOT NULL,
    [fecha_minima_solicitada]       DATE          NOT NULL,
    [fecha_maxima_solicitada]       DATE          NOT NULL,
    [hora_minima_solicitada]        TIME (0)      NOT NULL,
    [hora_maxima_solicitada]        TIME (0)      NOT NULL,
    [id_ciudad]                     BIGINT        NOT NULL,
    [ciudad_codigo_alterno]         VARCHAR (50)  NOT NULL,
    [ciudad_nombre_alterno]         VARCHAR (100) NOT NULL,
    [direccion]                     VARCHAR (150) NOT NULL,
    [punto_codigo_alterno]          VARCHAR (50)  NOT NULL,
    [punto_nombre_alterno]          VARCHAR (150) NOT NULL,
    [periodo]                       VARCHAR (50)  NOT NULL,
    [planta]                        VARCHAR (50)  NOT NULL,
    [identificador]                 VARCHAR (50)  NOT NULL,
    [programa_codigo]               VARCHAR (50)  NOT NULL,
    [programa]                      VARCHAR (50)  NOT NULL,
    [regional_codigo]               VARCHAR (50)  NOT NULL,
    [regional]                      VARCHAR (50)  NOT NULL,
    [centro_zonal]                  VARCHAR (50)  NOT NULL,
    [responsable_principal]         VARCHAR (150) NOT NULL,
    [responsable_suplente]          VARCHAR (150) NOT NULL,
    [telefono]                      VARCHAR (50)  NOT NULL,
    [ordnum]                        VARCHAR (35)  NULL,
    [wh_id]                         VARCHAR (32)  NULL,
    [client_id]                     VARCHAR (32)  NULL,
    [stgdte]                        DATETIME      NULL,
    [rmanum]                        VARCHAR (30)  NULL,
    [cliente_codigo_alterno_tms]    VARCHAR (50)  NULL,
    [remitente_identificacion]      VARCHAR (20)  NULL,
    [remitente_nombre]              VARCHAR (150) NULL,
    [remitente_departamento]        VARCHAR (50)  NULL,
    [remitente_ciudad]              VARCHAR (50)  NULL,
    [remitente_direccion]           VARCHAR (150) NULL,
    [remitente_telefono]            VARCHAR (50)  NULL,
    [remitente_contacto]            VARCHAR (150) NULL,
    [destinatario_identificacion]   VARCHAR (20)  NULL,
    [destinatario_nombre]           VARCHAR (150) NULL,
    [destinatario_departamento]     VARCHAR (60)  NULL,
    [destinatario_ciudad]           VARCHAR (50)  NULL,
    [destinatario_direccion]        VARCHAR (150) NULL,
    [destinatario_telefono]         VARCHAR (50)  NULL,
    [destinatario_contacto]         VARCHAR (150) NULL,
    [version]                       INT           CONSTRAINT [DF_solicitudes_actas_ingredion_version] DEFAULT ((0)) NOT NULL,
    [fecha_creacion]                DATETIME2 (0) CONSTRAINT [DF_solicitudes_actas_ingredion_fecha_creacion] DEFAULT (sysdatetime()) NOT NULL,
    [fecha_modificacion]            DATETIME2 (0) CONSTRAINT [DF_solicitudes_actas_ingredion_fecha_modificacion] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_solicitudes_actas_ingredion] PRIMARY KEY CLUSTERED ([id_solicitud_acta] ASC),
    CONSTRAINT [UK_solicitudes_actas_ingredion] UNIQUE NONCLUSTERED ([numero_solicitud] ASC, [id_cliente] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_solicitudes_actas_ingredion]
    ON [dbo].[solicitudes_actas_ingredion]([fecha_minima_solicitada] ASC, [fecha_maxima_solicitada] ASC, [id_bodega] ASC, [estado_solicitud] ASC);

