CREATE TABLE [dbo].[solicitudes] (
    [id_solicitud]                 BIGINT        NOT NULL,
    [integracion]                  VARCHAR (50)  NOT NULL,
    [correlacion]                  VARCHAR (100) NOT NULL,
    [id_externo]                   VARCHAR (100) NOT NULL,
    [tipo_solicitud]               VARCHAR (50)  NOT NULL,
    [estado_solicitud]             VARCHAR (50)  NOT NULL,
    [subestado_solicitud]          VARCHAR (50)  NOT NULL,
    [numero_solicitud]             VARCHAR (20)  NOT NULL,
    [prefijo]                      VARCHAR (20)  NOT NULL,
    [numero_solicitud_sin_prefijo] VARCHAR (20)  NOT NULL,
    [id_cliente]                   BIGINT        NOT NULL,
    [id_servicio]                  BIGINT        NOT NULL,
    [servicio_codigo_alterno]      VARCHAR (50)  NOT NULL,
    [id_bodega]                    BIGINT        NOT NULL,
    [id_bodega_traslado]           BIGINT        NULL,
    [id_tercero]                   BIGINT        NULL,
    [tercero_identificacion]       VARCHAR (20)  CONSTRAINT [DF__solicitud__terce__49E3F248] DEFAULT ('') NOT NULL,
    [tercero_nombre]               VARCHAR (100) CONSTRAINT [DF__solicitud__terce__4AD81681] DEFAULT ('') NOT NULL,
    [id_canal]                     BIGINT        NULL,
    [canal_codigo_alterno]         VARCHAR (50)  CONSTRAINT [DF__solicitud__canal__4BCC3ABA] DEFAULT ('') NOT NULL,
    [fecha_minima_solicitada]      DATE          NOT NULL,
    [fecha_maxima_solicitada]      DATE          NOT NULL,
    [hora_minima_solicitada]       TIME (0)      NULL,
    [hora_maxima_solicitada]       TIME (0)      NULL,
    [requiere_transporte]          BIT           NOT NULL,
    [requiere_recaudo]             BIT           NOT NULL,
    [nota]                         VARCHAR (200) CONSTRAINT [DF__solicitude__nota__4CC05EF3] DEFAULT ('') NOT NULL,
    [numero_solicitud_anulado]     VARCHAR (20)  CONSTRAINT [DF__solicitud__numer__2116E6DF] DEFAULT ('') NOT NULL,
    [id_causal_anulacion]          BIGINT        NULL,
    [nota_anulacion]               VARCHAR (200) CONSTRAINT [DF__solicitud__nota___220B0B18] DEFAULT ('') NOT NULL,
    [usuario_anulacion]            VARCHAR (50)  CONSTRAINT [DF__solicitud__usuar__22FF2F51] DEFAULT ('') NOT NULL,
    [fecha_anulacion]              DATETIME2 (0) NULL,
    [version]                      INT           CONSTRAINT [DF__solicitud__versi__23F3538A] DEFAULT ((0)) NOT NULL,
    [usuario_creacion]             VARCHAR (50)  NOT NULL,
    [fecha_creacion]               DATETIME2 (0) NOT NULL,
    [usuario_modificacion]         VARCHAR (50)  NOT NULL,
    [fecha_modificacion]           DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_solicitudes] PRIMARY KEY CLUSTERED ([id_solicitud] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_solicitudes_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_solicitudes_bodegas_traslado] FOREIGN KEY ([id_bodega_traslado]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_solicitudes_canales] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[canales] ([id_canal]),
    CONSTRAINT [FK_solicitudes_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_solicitudes_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_solicitudes_terceros] FOREIGN KEY ([id_tercero]) REFERENCES [dbo].[terceros] ([id_tercero]),
    CONSTRAINT [UK_solicitudes_01] UNIQUE NONCLUSTERED ([numero_solicitud] ASC, [id_cliente] ASC)
);



