CREATE TABLE [dbo].[solicitudes_geocodificacion] (
    [id_solicitud_geocodificacion]      BIGINT           IDENTITY (1, 1) NOT NULL,
    [id_orden_transporte]               BIGINT           NOT NULL,
    [id_tipo_documento]                 VARCHAR (20)     NOT NULL,
    [numero_documento]                  VARCHAR (20)     NOT NULL,
    [id_tipo_solicitud_geocodificacion] BIGINT           NOT NULL,
    [id_tipo_geocodificacion]           BIGINT           NULL,
    [estado]                            VARCHAR (50)     NOT NULL,
    [id_bodega]                         BIGINT           NOT NULL,
    [id_cliente]                        BIGINT           NOT NULL,
    [id_servicio]                       BIGINT           NOT NULL,
    [id_tercero]                        BIGINT           NULL,
    [tercero_codigo_alterno]            VARCHAR (20)     NOT NULL,
    [tercero_nombre]                    VARCHAR (100)    NOT NULL,
    [id_canal]                          BIGINT           NULL,
    [id_linea_negocio]                  BIGINT           NULL,
    [id_tipo_ruta]                      BIGINT           NULL,
    [fecha_minima_solicitada]           DATE             NULL,
    [fecha_maxima_solicitada]           DATE             NULL,
    [id_ciudad]                         BIGINT           NOT NULL,
    [direccion]                         VARCHAR (150)    NOT NULL,
    [id_direccion]                      BIGINT           NULL,
    [direccion_estandarizada]           VARCHAR (150)    NOT NULL,
    [cx]                                DECIMAL (18, 15) NULL,
    [cy]                                DECIMAL (18, 15) NULL,
    [zona]                              VARCHAR (100)    NOT NULL,
    [localidad]                         VARCHAR (100)    NOT NULL,
    [barrio]                            VARCHAR (100)    NOT NULL,
    [nota_cierre]                       VARCHAR (200)    NOT NULL,
    [usuario_cierre]                    VARCHAR (50)     NOT NULL,
    [fecha_cierre]                      DATETIME2 (0)    NULL,
    [bloquear_direccion]                BIT              NOT NULL,
    [id_causal_anulacion]               BIGINT           NULL,
    [nota_anulacion]                    VARCHAR (200)    NOT NULL,
    [usuario_anulacion]                 VARCHAR (50)     NOT NULL,
    [fecha_anulacion]                   DATETIME2 (0)    NULL,
    [version]                           INT              NOT NULL,
    [usuario_creacion]                  VARCHAR (50)     NOT NULL,
    [fecha_creacion]                    DATETIME2 (0)    NOT NULL,
    [usuario_modificacion]              VARCHAR (50)     NOT NULL,
    [fecha_modificacion]                DATETIME2 (0)    NOT NULL,
    CONSTRAINT [PK_solicitudes_geocodificacion] PRIMARY KEY CLUSTERED ([id_orden_transporte] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_solicitudes_geocodificacion_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_solicitudes_geocodificacion_canales] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[canales] ([id_canal]),
    CONSTRAINT [FK_solicitudes_geocodificacion_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_solicitudes_geocodificacion_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_solicitudes_geocodificacion_terceros] FOREIGN KEY ([id_tercero]) REFERENCES [dbo].[terceros] ([id_tercero]),
    CONSTRAINT [FK_solicitudes_geocodificacion_tipos_identificacion] FOREIGN KEY ([id_tipo_documento]) REFERENCES [dbo].[tipos_identificacion] ([id_tipo_identificacion])
);

