CREATE TABLE [wms].[saldos_inventario] (
    [id]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [id_archivo]              BIGINT          NOT NULL,
    [estado]                  VARCHAR (50)    NOT NULL,
    [numero_linea]            INT             NOT NULL,
    [cliente_codigo]          VARCHAR (20)    NOT NULL,
    [fecha]                   DATE            NULL,
    [producto_codigo_alterno] VARCHAR (50)    NOT NULL,
    [producto_nombre]         VARCHAR (200)   NOT NULL,
    [bodega_codigo_alterno]   VARCHAR (50)    NOT NULL,
    [bodega_nombre]           VARCHAR (50)    NOT NULL,
    [unidad_codigo_alterno]   VARCHAR (50)    NOT NULL,
    [unidades_por_empaque]    INT             NULL,
    [cantidad]                DECIMAL (12, 4) NOT NULL,
    [valor_unitario]          DECIMAL (12, 4) NULL,
    [id_cliente]              BIGINT          NULL,
    [id_producto]             BIGINT          NULL,
    [id_bodega]               BIGINT          NULL,
    [id_estado_inventario]    VARCHAR (50)    NULL,
    [id_unidad]               BIGINT          NULL,
    [version]                 INT             NOT NULL,
    [fecha_creacion]          DATETIME2 (0)   NOT NULL,
    [usuario_creacion]        VARCHAR (50)    NOT NULL,
    [fecha_modificacion]      DATETIME2 (0)   NOT NULL,
    [usuario_modificacion]    VARCHAR (50)    NOT NULL,
    CONSTRAINT [PK_saldos_inventario] PRIMARY KEY CLUSTERED ([id] ASC)
);

