CREATE TABLE [oms].[destrucciones] (
    [id]                               BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_archivo]                       BIGINT        NOT NULL,
    [estado]                           VARCHAR (50)  NOT NULL,
    [numero_linea]                     INT           NOT NULL,
    [cliente_codigo]                   VARCHAR (20)  NOT NULL,
    [servicio_codigo_alterno]          VARCHAR (50)  NOT NULL,
    [numero_orden]                     VARCHAR (20)  NOT NULL,
    [prefijo_orden]                    VARCHAR (20)  NOT NULL,
    [numero_orden_sin_prefijo]         VARCHAR (20)  NOT NULL,
    [femi]                             DATE          NULL,
    [fema]                             DATE          NULL,
    [producto_codigo_alterno]          VARCHAR (50)  NOT NULL,
    [producto_nombre]                  VARCHAR (200) NOT NULL,
    [cantidad]                         INT           NOT NULL,
    [unidad_codigo_alterno]            VARCHAR (50)  NOT NULL,
    [bodega_codigo_alterno]            VARCHAR (50)  NOT NULL,
    [estado_inventario_codigo_alterno] VARCHAR (50)  NOT NULL,
    [lote]                             VARCHAR (30)  NOT NULL,
    [id_cliente]                       BIGINT        NULL,
    [id_servicio]                      BIGINT        NULL,
    [id_producto]                      BIGINT        NULL,
    [id_unidad]                        BIGINT        NULL,
    [id_bodega]                        BIGINT        NULL,
    [id_estado_inventario]             VARCHAR (50)  NULL,
    [version]                          INT           NOT NULL,
    [fecha_creacion]                   DATETIME2 (0) NOT NULL,
    [usuario_creacion]                 VARCHAR (50)  NOT NULL,
    [fecha_modificacion]               DATETIME2 (0) NOT NULL,
    [usuario_modificacion]             VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_destrucciones] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 80)
);

