CREATE TABLE [dbo].[ordenes_alistamiento] (
    [id_orden_alistamiento]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_solicitud]             BIGINT        NOT NULL,
    [estado]                   VARCHAR (50)  NOT NULL,
    [numero_orden]             VARCHAR (35)  NOT NULL,
    [id_cliente]               BIGINT        NOT NULL,
    [id_servicio]              BIGINT        NOT NULL,
    [id_linea_negocio]         BIGINT        NOT NULL,
    [id_solicitud_orden]       BIGINT        NOT NULL,
    [id_bodega]                BIGINT        NOT NULL,
    [id_tercero]               BIGINT        NULL,
    [tercero_identificacion]   VARCHAR (20)  NOT NULL,
    [tercero_nombre]           VARCHAR (100) NOT NULL,
    [id_canal]                 BIGINT        NULL,
    [fecha_minima_solicitada]  DATE          NOT NULL,
    [fecha_maxima_solicitada]  DATE          NOT NULL,
    [hora_minima_solicitada]   TIME (0)      NULL,
    [hora_maxima_solicitada]   TIME (0)      NULL,
    [fecha_cita_entrega]       DATE          NULL,
    [hora_cita_entrega_minima] TIME (0)      NULL,
    [hora_cita_entrega_maxima] TIME (0)      NULL,
    [requiere_transporte]      BIT           NOT NULL,
    [id_ciudad_destinatario]   BIGINT        NULL,
    [direccion_destinatario]   VARCHAR (150) NOT NULL,
    [nota]                     VARCHAR (200) NOT NULL,
    [id_causal_anulacion]      BIGINT        NULL,
    [nota_cierre]              VARCHAR (200) CONSTRAINT [DF__tmp_ms_xx__nota___32767D0B] DEFAULT ('') NOT NULL,
    [cerrada]                  BIT           CONSTRAINT [DF__tmp_ms_xx__cerra__336AA144] DEFAULT ((0)) NOT NULL,
    [cierre_notificado]        BIT           CONSTRAINT [DF__tmp_ms_xx__cierr__345EC57D] DEFAULT ((0)) NOT NULL,
    [usuario_cierre]           VARCHAR (50)  CONSTRAINT [DF__tmp_ms_xx__usuar__3552E9B6] DEFAULT ('') NOT NULL,
    [fecha_cierre]             DATETIME2 (0) NULL,
    [version]                  INT           CONSTRAINT [DF__tmp_ms_xx__versi__36470DEF] DEFAULT ((0)) NOT NULL,
    [usuario_creacion]         VARCHAR (50)  NOT NULL,
    [fecha_creacion]           DATETIME2 (0) NOT NULL,
    [usuario_modificacion]     VARCHAR (50)  NOT NULL,
    [fecha_modificacion]       DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_ordenes_alistamiento] PRIMARY KEY CLUSTERED ([id_orden_alistamiento] ASC),
    CONSTRAINT [FK_ordenes_alistamiento_bodegas] FOREIGN KEY ([id_bodega]) REFERENCES [dbo].[bodegas] ([id_bodega]),
    CONSTRAINT [FK_ordenes_alistamiento_canales] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[canales] ([id_canal]),
    CONSTRAINT [FK_ordenes_alistamiento_ciudades] FOREIGN KEY ([id_ciudad_destinatario]) REFERENCES [dbo].[ciudades] ([id_ciudad]),
    CONSTRAINT [FK_ordenes_alistamiento_clientes] FOREIGN KEY ([id_cliente]) REFERENCES [dbo].[clientes] ([id_cliente]),
    CONSTRAINT [FK_ordenes_alistamiento_lineas_negocio] FOREIGN KEY ([id_linea_negocio]) REFERENCES [dbo].[lineas_negocio] ([id_linea_negocio]),
    CONSTRAINT [FK_ordenes_alistamiento_servicios] FOREIGN KEY ([id_servicio]) REFERENCES [dbo].[servicios] ([id_servicio]),
    CONSTRAINT [FK_ordenes_alistamiento_solicitudes] FOREIGN KEY ([id_solicitud]) REFERENCES [dbo].[solicitudes] ([id_solicitud]),
    CONSTRAINT [FK_ordenes_alistamiento_solicitudes_ordenes] FOREIGN KEY ([id_solicitud_orden]) REFERENCES [dbo].[solicitudes_ordenes] ([id_solicitud_orden]),
    CONSTRAINT [FK_ordenes_alistamiento_terceros] FOREIGN KEY ([id_tercero]) REFERENCES [dbo].[terceros] ([id_tercero]),
    CONSTRAINT [UK_ordenes_alistamiento_01] UNIQUE NONCLUSTERED ([id_cliente] ASC, [numero_orden] ASC)
);

