CREATE TABLE [ordenes].[lineas_orden] (
    [id_linea_orden]                   INT              IDENTITY (1, 1) NOT NULL,
    [id_orden]                         INT              NOT NULL,
    [notas]                            VARCHAR (200)    NOT NULL,
    [numero_item]                      INT              NOT NULL,
    [descripcion]                      VARCHAR (200)    NOT NULL,
    [cantidad]                         INT              NOT NULL,
    [id_producto]                      INT              NULL,
    [codigo_producto]                  VARCHAR (50)     NOT NULL,
    [codigo_alterno_producto]          VARCHAR (50)     NOT NULL,
    [id_unidad]                        INT              NULL,
    [codigo_unidad]                    VARCHAR (20)     NOT NULL,
    [codigo_alterno_unidad]            VARCHAR (20)     NOT NULL,
    [id_bodega_origen]                 INT              NULL,
    [bodega_origen_codigo_alterno]     VARCHAR (20)     NOT NULL,
    [bodega_origen_nombre_alterno]     VARCHAR (100)    NULL,
    [id_estado_inventario]             VARCHAR (50)     NULL,
    [origen_nombre_alterno]            VARCHAR (100)    NULL,
    [id_bodega_destino]                INT              NULL,
    [bodega_destino_codigo]            VARCHAR (32)     NULL,
    [bodega_destino_codigo_alterno]    VARCHAR (50)     NULL,
    [id_estado_inventario_destino]     VARCHAR (4)      NULL,
    [valor_declarado_por_unidad]       INT              NULL,
    [predistribucion_rotulo]           VARCHAR (100)    NULL,
    [predistribucion_destino_final]    VARCHAR (100)    NULL,
    [lote]                             VARCHAR (30)     NOT NULL,
    [serial]                           VARCHAR (30)     NULL,
    [cosecha]                          VARCHAR (30)     NULL,
    [requerimiento_bl]                 VARCHAR (30)     NULL,
    [requerimiento_distribuido]        VARCHAR (30)     NULL,
    [requerimiento_estampillado]       VARCHAR (30)     NULL,
    [requerimiento_fondo_cuenta]       VARCHAR (30)     NULL,
    [requerimiento_importe]            VARCHAR (30)     NULL,
    [requerimiento_nutricional]        VARCHAR (30)     NULL,
    [requerimiento_origen]             VARCHAR (30)     NULL,
    [requerimiento_salud]              VARCHAR (30)     NULL,
    [fecha_actualizacion]              DATETIME2 (0)    NOT NULL,
    [usuario_actualizacion]            VARCHAR (50)     NOT NULL,
    [alto_por_unidad]                  NUMERIC (12, 4)  NULL,
    [ancho_por_unidad]                 NUMERIC (12, 4)  NULL,
    [largo_por_unidad]                 NUMERIC (12, 4)  NULL,
    [peso_bruto_por_unidad]            NUMERIC (12, 4)  NULL,
    [numero_orden_wms_destino]         VARCHAR (35)     NULL,
    [numero_orden_wms_origen]          VARCHAR (35)     NULL,
    [consistente]                      BIT              NOT NULL,
    [origen_codigo_alterno]            VARCHAR (20)     NULL,
    [origen_contacto_email]            VARCHAR (100)    NULL,
    [origen_contacto_nombres]          VARCHAR (100)    NULL,
    [origen_contacto_telefonos]        VARCHAR (50)     NULL,
    [origen_direccion]                 VARCHAR (150)    NULL,
    [origen_direccion_estandarizada]   VARCHAR (150)    NULL,
    [origen_indicaciones_direccion]    VARCHAR (150)    NULL,
    [origen_latitud]                   NUMERIC (18, 15) NULL,
    [origen_longitud]                  NUMERIC (18, 15) NULL,
    [id_destino_origen_origen]         INT              NULL,
    [id_ciudad_origen]                 INT              NULL,
    [id_tipo_contenido]                INT              NULL,
    [cantidad_planificada]             INT              NULL,
    [cantidad_autorizada]              INT              NULL,
    [cantidad_alistada]                INT              NULL,
    [cantidad_no_alistada]             INT              NULL,
    [cantidad_sobrante]                INT              NULL,
    [cantidad_faltante]                INT              NULL,
    [cantidad_entregada]               INT              NULL,
    [cantidad_no_entregada]            INT              NULL,
    [cantidad_sobrante_legalizada]     INT              NULL,
    [cantidad_no_entregada_legalizada] INT              NULL,
    [valor_venta_por_unidad]           INT              NULL,
    [numero_documento_entrega_cliente] VARCHAR (30)     NULL,
    [fecha_documento_entrega_cliente]  DATE             NULL,
    [requiere_servicio_estampillado]   BIT              NULL,
    [rotulo]                           DATE             NULL,
    CONSTRAINT [PK_lineas_orden] PRIMARY KEY CLUSTERED ([id_linea_orden] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [CK_lineas_orden] CHECK ([numero_item]<=(9999)),
    CONSTRAINT [FK_lineas_orden_06] FOREIGN KEY ([id_orden]) REFERENCES [ordenes].[ordenes] ([id_orden])
)