CREATE TABLE [tms].[cumplidos_rutacontrol] (
    [id]                                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [id_archivo]                           BIGINT         NOT NULL,
    [estado]                               VARCHAR (50)   NOT NULL,
    [numero_linea]                         INT            NOT NULL,
    [cliente_identificacion]               VARCHAR (20)   NOT NULL,
    [numero_orden]                         VARCHAR (20)   NOT NULL,
    [placa]                                VARCHAR (20)   NOT NULL,
    [estado_remesa_codigo_alterno]         VARCHAR (50)   NOT NULL,
    [fecha_hora_inicio_visita]             DATETIME2 (0)  NULL,
    [fecha_hora_fin_visita]                DATETIME2 (0)  NULL,
    [causal_novedad_remesa_codigo_alterno] VARCHAR (50)   NOT NULL,
    [valor_recaudado]                      INT            NULL,
    [observaciones]                        VARCHAR (1000) NOT NULL,
    [responsable_directo_codigo_alterno]   VARCHAR (50)   NOT NULL,
    [responsable_interno_codigo_alterno]   VARCHAR (50)   NOT NULL,
    [fecha_reprogramacion]                 DATE           NULL,
    [homi_reprogramacion]                  TIME (0)       NULL,
    [homa_reprogramacion]                  TIME (0)       NULL,
    [id_cliente]                           BIGINT         NULL,
    [id_orden]                             BIGINT         NULL,
    [id_estado_remesa]                     VARCHAR (50)   NULL,
    [id_causal_novedad_remesa]             BIGINT         NULL,
    [id_responsable_directo]               BIGINT         NULL,
    [id_responsable_interno]               BIGINT         NULL,
    [version]                              INT            NOT NULL,
    [fecha_creacion]                       DATETIME2 (0)  NOT NULL,
    [usuario_creacion]                     VARCHAR (50)   NOT NULL,
    [fecha_modificacion]                   DATETIME2 (0)  NOT NULL,
    [usuario_modificacion]                 VARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_cumplidos_rutacontrol] PRIMARY KEY CLUSTERED ([id] ASC)
);



