CREATE TABLE [dbo].[lineas_orden] (
    [id_solicitud]                  BIGINT          NOT NULL,
    [numero_item]                   INT             NOT NULL,
    [notas]                         VARCHAR (200)   NOT NULL,
    [descripcion]                   VARCHAR (200)   NOT NULL,
    [cantidad]                      INT             NOT NULL,
    [id_producto]                   INT             NOT NULL,
    [codigo_producto]               VARCHAR (50)    NOT NULL,
    [id_unidad]                     INT             NOT NULL,
    [codigo_unidad]                 VARCHAR (20)    NOT NULL,
    [bodega_origen_codigo_alterno]  VARCHAR (20)    NOT NULL,
    [id_bodega_origen]              INT             NOT NULL,
    [id_estado_inventario]          VARCHAR (50)    NOT NULL,
    [bodega_origen_nombre_alterno]  VARCHAR (100)   NOT NULL,
    [valor_declarado_por_unidad]    INT             NULL,
    [predistribucion_rotulo]        VARCHAR (100)   NOT NULL,
    [predistribucion_destino_final] VARCHAR (100)   NOT NULL,
    [lote]                          VARCHAR (30)    NOT NULL,
    [fecha_actualizacion]           DATETIME2 (0)   NOT NULL,
    [usuario_actualizacion]         VARCHAR (50)    NOT NULL,
    [alto_por_unidad]               NUMERIC (12, 4) NULL,
    [ancho_por_unidad]              NUMERIC (12, 4) NULL,
    [largo_por_unidad]              NUMERIC (12, 4) NULL,
    [peso_bruto_por_unidad]         NUMERIC (12, 4) NULL,
    [consistente]                   BIT             NOT NULL,
    CONSTRAINT [PK_lineas_orden_1] PRIMARY KEY CLUSTERED ([id_solicitud] ASC, [numero_item] ASC),
    CONSTRAINT [FK_lineas_orden_ordenes] FOREIGN KEY ([id_solicitud]) REFERENCES [dbo].[ordenes] ([id_solicitud]) ON DELETE CASCADE
);

