CREATE TABLE [dbo].[mensajes_ordenes_transporte] (
    [id_mensaje]                  BIGINT           IDENTITY (1, 1) NOT NULL,
    [fecha_creacion]              DATETIME2 (7)    NOT NULL,
    [fecha_modificacion]          DATETIME2 (7)    NULL,
    [centro_costo]                VARCHAR (30)     NULL,
    [tipo_remesa]                 VARCHAR (20)     NULL,
    [codigo_cliente]              VARCHAR (32)     NULL,
    [division_cliente]            VARCHAR (45)     NULL,
    [nombre_remitente]            VARCHAR (100)    NULL,
    [tipo_documento_remitente]    VARCHAR (100)    NULL,
    [documento_remitente]         VARCHAR (20)     NULL,
    [direccion_remitente]         VARCHAR (150)    NULL,
    [telefono_remitente]          VARCHAR (100)    NULL,
    [contacto_remitente]          VARCHAR (100)    NULL,
    [ciudad_remitente]            VARCHAR (100)    NULL,
    [departamento_remitente]      VARCHAR (100)    NULL,
    [nombre_destinatario]         VARCHAR (100)    NULL,
    [tipo_documento_destinatario] VARCHAR (100)    NULL,
    [documento_destinatario]      VARCHAR (20)     NULL,
    [direccion_destinatario]      VARCHAR (150)    NULL,
    [telefono_destinatario]       VARCHAR (100)    NULL,
    [contacto_destinatario1]      VARCHAR (100)    NULL,
    [contacto_destinatario2]      VARCHAR (100)    NULL,
    [ciudad_destinatario]         VARCHAR (100)    NULL,
    [departamento_destinatario]   VARCHAR (100)    NULL,
    [zona_ciudad_destinatario]    VARCHAR (100)    NULL,
    [coordenada_x_longitud]       DECIMAL (18, 15) NULL,
    [coordenada_y_latitud]        DECIMAL (18, 15) NULL,
    [observacion_remesa]          VARCHAR (100)    NULL,
    [fecha_compromiso_minima]     VARCHAR (30)     NULL,
    [fecha_compromiso_maxima]     VARCHAR (30)     NULL,
    [hora_compromiso_maxima]      VARCHAR (30)     NULL,
    [hora_compromiso_minima]      VARCHAR (30)     NULL,
    [placa_vehiculo]              VARCHAR (100)    NULL,
    [secuencia_entrega]           VARCHAR (100)    NULL,
    [tipo_remision]               VARCHAR (3)      NULL,
    [remision]                    VARCHAR (50)     NULL,
    [documento_wms]               VARCHAR (50)     NULL,
    [documento_numero_solicitud]  VARCHAR (20)     NULL,
    [id_ordentransporte]          BIGINT           NULL,
    [punto_codigo_alterno]        VARCHAR (50)     NULL,
    [regional]                    VARCHAR (50)     NULL,
    [ciudad_nombre_alterno]       VARCHAR (50)     NULL,
    [bodega_codigo_alterno]       VARCHAR (50)     NULL,
    [programa]                    VARCHAR (50)     NULL,
    [planta]                      VARCHAR (50)     NULL,
    [id_envio_ordenes_transporte] BIGINT           NULL,
    CONSTRAINT [PK_mensajes_ordenes_transporte] PRIMARY KEY CLUSTERED ([id_mensaje] ASC)
);

