CREATE TABLE [dbo].[solicitudes_actas_ingredion] (
    [id_solicitud_acta]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [id_cliente]            BIGINT        NOT NULL,
    [numero_solicitud]      VARCHAR (20)  NOT NULL,
    [estado]                VARCHAR (50)  NOT NULL,
    [periodo]               VARCHAR (50)  NOT NULL,
    [planta]                VARCHAR (50)  NOT NULL,
    [bodega_codigo_alterno] VARCHAR (50)  NOT NULL,
    [fecha_inicial]         DATE          NOT NULL,
    [fecha_final]           DATE          NOT NULL,
    [identificador]         VARCHAR (50)  NOT NULL,
    [programa_codigo]       VARCHAR (50)  NOT NULL,
    [programa]              VARCHAR (50)  NOT NULL,
    [regional_codigo]       VARCHAR (50)  NOT NULL,
    [regional]              VARCHAR (50)  NOT NULL,
    [centro_zonal]          VARCHAR (50)  NOT NULL,
    [ciudad_codigo_alterno] VARCHAR (50)  NOT NULL,
    [ciudad_nombre_alterno] VARCHAR (100) NOT NULL,
    [direccion]             VARCHAR (150) NOT NULL,
    [punto_codigo_alterno]  VARCHAR (50)  NOT NULL,
    [punto_nombre_alterno]  VARCHAR (150) NOT NULL,
    [responsable_principal] VARCHAR (150) NOT NULL,
    [responsable_suplente]  VARCHAR (150) NOT NULL,
    [telefono]              VARCHAR (50)  NOT NULL,
    [id_bodega]             BIGINT        NULL,
    [id_ciudad]             BIGINT        NULL,
    [id_orden]              BIGINT        NULL,
    [ordnum]                VARCHAR (35)  NULL,
    [wh_id]                 VARCHAR (32)  NULL,
    [version]               INT           CONSTRAINT [DF_solicitudes_actas_ingredion_version] DEFAULT ((0)) NOT NULL,
    [fecha_creacion]        DATETIME2 (0) CONSTRAINT [DF_solicitudes_actas_ingredion_fecha_creacion] DEFAULT (sysdatetime()) NOT NULL,
    [fecha_modificacion]    DATETIME2 (0) CONSTRAINT [DF_solicitudes_actas_ingredion_fecha_modificacion] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_solicitudes_actas_ingredion] PRIMARY KEY CLUSTERED ([id_solicitud_acta] ASC),
    CONSTRAINT [UK_solicitudes_actas_ingredion] UNIQUE NONCLUSTERED ([numero_solicitud] ASC, [id_cliente] ASC)
);

