CREATE TABLE [dbo].[solicitudes_despacho] (
    [id_solicitud_despacho]        BIGINT        NOT NULL,
    [integracion]                  VARCHAR (50)  NOT NULL,
    [correlacion]                  VARCHAR (100) NOT NULL,
    [id_externo]                   VARCHAR (100) NOT NULL,
    [cliente_codigo_alterno]       VARCHAR (50)  NOT NULL,
    [servicio_codigo_alterno]      VARCHAR (50)  NOT NULL,
    [numero_solicitud]             VARCHAR (20)  NOT NULL,
    [prefijo]                      VARCHAR (20)  NOT NULL,
    [numero_solicitud_sin_prefijo] VARCHAR (20)  NOT NULL,
    [femi]                         DATE          NULL,
    [fema]                         DATE          NULL,
    [homi]                         TIME (0)      NULL,
    [homa]                         TIME (0)      NULL,
    [requiere_transporte]          BIT           NOT NULL,
    [requiere_agendamiento]        BIT           NOT NULL,
    [requiere_despachar_completo]  BIT           NOT NULL,
    [tercero_identificacion]       VARCHAR (20)  NOT NULL,
    [tercero_nombre]               VARCHAR (100) NOT NULL,
    [canal_codigo_alterno]         VARCHAR (50)  NOT NULL,
    [ciudad_codigo_alterno]        VARCHAR (50)  NOT NULL,
    [direccion]                    VARCHAR (150) NOT NULL,
    [punto_codigo_alterno]         VARCHAR (50)  NOT NULL,
    [punto_nombre]                 VARCHAR (100) NOT NULL,
    [autorizado_identificacion]    VARCHAR (20)  NOT NULL,
    [autorizado_nombres]           VARCHAR (100) NOT NULL,
    [numero_orden_compra]          VARCHAR (20)  NOT NULL,
    [fecha_orden_compra]           DATE          NULL,
    [nota]                         VARCHAR (200) NOT NULL,
    [id_cliente]                   BIGINT        NULL,
    [id_servicio]                  BIGINT        NULL,
    [id_tercero]                   BIGINT        NULL,
    [id_canal]                     BIGINT        NULL,
    [id_ciudad]                    BIGINT        NULL,
    [id_punto]                     BIGINT        NULL,
    [fecha_creacion_externa]       DATETIME2 (0) NULL,
    [version]                      INT           NOT NULL,
    [fecha_creacion]               DATETIME2 (0) NOT NULL,
    [fecha_modificacion]           DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_solicitudes_despacho] PRIMARY KEY CLUSTERED ([id_solicitud_despacho] ASC)
);



